package com.redhat;

rule "Filter businesses from Kansas"
ruleflow-group "filter"
dialect "mvel"

	when
    $business: Business(stateCode == "KS")
	then
    insert(false);
    Reason reason = new Reason("business filtered from Kansas");
		reason.setStatusCode("filtered");
    insert(reason);
end

rule "Make all other states succeed"
ruleflow-group "filter"
dialect "mvel"

	when
		$business : Business(stateCode != "KS")
	then
		insert(true);
end
